import argparse
import os
import pickle

import matplotlib.pyplot as plt
import numpy as np


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Load pi-band pickle data and compare linear vs quadratic fits "
            "for each pi band on a 1D k-space cut."
        )
    )
    parser.add_argument(
        "--pickle",
        default=None,
        help="Path to pickle generated by plot_pi_bands_from_projwfc.py.",
    )
    parser.add_argument(
        "--prefix",
        default=None,
        help=(
            "Projection prefix, e.g. proj15.0upper. If --pickle is not set, "
            "script looks for <proj-dir>/<prefix>_pi_data.pkl."
        ),
    )
    parser.add_argument(
        "--proj-dir",
        default="projections",
        help="Directory used with --prefix to locate pickle files (default: projections).",
    )
    parser.add_argument(
        "--axis",
        choices=["kx", "ky"],
        default="kx",
        help="Sweep axis for fitting (default: kx).",
    )
    parser.add_argument(
        "--fixed",
        type=float,
        default=None,
        help=(
            "Fixed value for the other axis. "
            "If omitted, inferred from minimum pi-gap location."
        ),
    )
    parser.add_argument(
        "--fermi",
        type=float,
        default=None,
        help="Optional Fermi energy (eV) to plot/fit E-Ef.",
    )
    parser.add_argument(
        "--min-points",
        type=int,
        default=6,
        help="Minimum data points required to fit a band (default: 6).",
    )
    parser.add_argument(
        "--savefig",
        default=None,
        help="Output figure path (default: <pickle_stem>_pi_fit_<axis>.png).",
    )
    return parser.parse_args()


def load_payload(path):
    with open(path, "rb") as f:
        payload = pickle.load(f)
    required = ["k_points", "pi_bands"]
    for key in required:
        if key not in payload:
            raise ValueError(f"Missing key in pickle: '{key}'")
    k_points = np.asarray(payload["k_points"], dtype=float)
    pi_bands = np.asarray(payload["pi_bands"], dtype=float)
    if k_points.ndim != 2 or k_points.shape[1] < 2:
        raise ValueError("k_points must have shape (N, >=2).")
    if pi_bands.ndim != 2:
        raise ValueError("pi_bands must have shape (N_pi, N).")
    if pi_bands.shape[1] != k_points.shape[0]:
        raise ValueError("pi_bands second dimension must match number of k_points.")
    return payload, k_points, pi_bands


def resolve_pickle_path(args):
    if args.pickle:
        return args.pickle
    if not args.prefix:
        raise ValueError("Provide either --pickle or --prefix.")

    candidates = [
        os.path.join(args.proj_dir, f"{args.prefix}_pi_data.pkl"),
        f"{args.prefix}_pi_data.pkl",
    ]
    for cand in candidates:
        if os.path.exists(cand):
            return cand
    return candidates[0]


def infer_cut_value(k_points, pi_bands, axis):
    # Use smallest direct gap between first two available pi bands.
    if pi_bands.shape[0] < 2:
        return float(np.median(k_points[:, 1 if axis == "kx" else 0]))

    e1 = pi_bands[0]
    e2 = pi_bands[1]
    valid = np.isfinite(e1) & np.isfinite(e2)
    if not np.any(valid):
        return float(np.median(k_points[:, 1 if axis == "kx" else 0]))

    gap = np.abs(e2[valid] - e1[valid])
    local_idx = int(np.argmin(gap))
    global_idx = np.where(valid)[0][local_idx]
    # axis kx => fixed ky; axis ky => fixed kx
    fixed_col = 1 if axis == "kx" else 0
    return float(k_points[global_idx, fixed_col])


def build_cut_indices(k_points, axis, fixed_target):
    if axis == "kx":
        sweep_col, fixed_col = 0, 1
    else:
        sweep_col, fixed_col = 1, 0

    unique_fixed = np.unique(np.round(k_points[:, fixed_col], 12))
    fixed_value = float(unique_fixed[np.argmin(np.abs(unique_fixed - fixed_target))])
    mask = np.isclose(k_points[:, fixed_col], fixed_value, atol=1e-10)
    idx = np.where(mask)[0]
    order = np.argsort(k_points[idx, sweep_col])
    idx = idx[order]
    x = k_points[idx, sweep_col]
    return idx, x, fixed_value


def fit_band(x, y):
    coeff_lin = np.polyfit(x, y, deg=1)
    coeff_quad = np.polyfit(x, y, deg=2)
    y_lin = np.polyval(coeff_lin, x)
    y_quad = np.polyval(coeff_quad, x)

    def metrics(y_true, y_pred):
        resid = y_true - y_pred
        ss_res = float(np.sum(resid * resid))
        y_mean = float(np.mean(y_true))
        ss_tot = float(np.sum((y_true - y_mean) ** 2))
        rmse = float(np.sqrt(np.mean(resid * resid)))
        r2 = float(1.0 - ss_res / ss_tot) if ss_tot > 0 else np.nan
        return rmse, r2

    lin_rmse, lin_r2 = metrics(y, y_lin)
    quad_rmse, quad_r2 = metrics(y, y_quad)
    better = "quadratic" if quad_rmse < lin_rmse else "linear"

    return {
        "coeff_lin": coeff_lin,
        "coeff_quad": coeff_quad,
        "y_lin": y_lin,
        "y_quad": y_quad,
        "lin_rmse": lin_rmse,
        "lin_r2": lin_r2,
        "quad_rmse": quad_rmse,
        "quad_r2": quad_r2,
        "better": better,
    }


def main():
    args = parse_args()
    try:
        pickle_path = resolve_pickle_path(args)
    except ValueError as exc:
        print(f"Error: {exc}")
        return

    try:
        payload, k_points, pi_bands = load_payload(pickle_path)
    except (ValueError, OSError, pickle.PickleError) as exc:
        print(f"Error: {exc}")
        return

    fixed_target = args.fixed if args.fixed is not None else infer_cut_value(k_points, pi_bands, args.axis)
    cut_idx, x, fixed_value = build_cut_indices(k_points, args.axis, fixed_target)
    if x.size < args.min_points:
        print(f"Error: cut has only {x.size} points; need at least {args.min_points}.")
        return

    fig, ax = plt.subplots(figsize=(10, 6))
    colors = ["tab:blue", "tab:red", "tab:green", "tab:purple", "tab:orange", "tab:brown"]
    x_dense = np.linspace(float(np.min(x)), float(np.max(x)), 400)

    fit_summaries = []
    for band_i in range(pi_bands.shape[0]):
        y = pi_bands[band_i, cut_idx]
        valid = np.isfinite(y)
        if np.count_nonzero(valid) < args.min_points:
            continue

        xv = x[valid]
        yv = y[valid]
        if args.fermi is not None:
            yv = yv - args.fermi

        fit = fit_band(xv, yv)
        fit_summaries.append((band_i + 1, fit))

        color = colors[band_i % len(colors)]
        ax.scatter(xv, yv, s=16, color=color, alpha=0.8, label=f"pi rank {band_i + 1} data")
        ax.plot(
            x_dense,
            np.polyval(fit["coeff_lin"], x_dense),
            color=color,
            lw=1.5,
            ls="--",
            alpha=0.9,
            label=f"pi rank {band_i + 1} linear",
        )
        ax.plot(
            x_dense,
            np.polyval(fit["coeff_quad"], x_dense),
            color=color,
            lw=1.8,
            ls="-",
            alpha=0.9,
            label=f"pi rank {band_i + 1} quadratic",
        )

    if not fit_summaries:
        print("Error: no pi bands on selected cut with enough finite points to fit.")
        return

    xlabel = r"$k_x$ (tpiba)" if args.axis == "kx" else r"$k_y$ (tpiba)"
    fixed_label = "ky" if args.axis == "kx" else "kx"
    ylabel = r"$E - E_F$ (eV)" if args.fermi is not None else r"$E$ (eV)"
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(f"Pi-band fits along {args.axis} cut at {fixed_label}={fixed_value:.6f}")
    ax.grid(alpha=0.25)
    if args.fermi is not None:
        ax.axhline(0.0, color="gray", lw=1.0, ls=":")
    ax.legend(fontsize=8, ncol=2)

    pstem = os.path.splitext(os.path.basename(pickle_path))[0]
    savefig = args.savefig if args.savefig else f"{pstem}_pi_fit_{args.axis}.png"
    plt.tight_layout()
    plt.savefig(savefig, dpi=300, bbox_inches="tight")

    print(f"Saved fit plot: {savefig}")
    print(f"Info: axis={args.axis}, fixed_{fixed_label}={fixed_value:.8f}, n_points={x.size}")
    for rank, fit in fit_summaries:
        print(
            f"pi rank {rank}: "
            f"linear RMSE={fit['lin_rmse']:.6e}, R2={fit['lin_r2']:.6f}; "
            f"quadratic RMSE={fit['quad_rmse']:.6e}, R2={fit['quad_r2']:.6f}; "
            f"better={fit['better']}"
        )

    meta = payload.get("meta", {})
    if meta:
        print(f"Meta: source={meta.get('proj_out', 'unknown')}, selection_mode={meta.get('selection_mode', 'unknown')}")


if __name__ == "__main__":
    main()
